[package]
name = "kitsune-captcha"
version.workspace = true
edition = "2021"

[dependencies]
async-trait = "0.1.73"
enum_dispatch = "0.3.12"
http = "0.2.9"
http-body = "0.4.5"
hyper = { version = "0.14.27", features = [
    "client",
    "deprecated",
    "http1",
    "http2",
    "runtime",
] }
hyper-rustls = { version = "0.24.1", features = ["http2"] }
kitsune-http-client = { path = "../kitsune-http-client" }
serde = { version = "1.0.183", features = ["derive"] }
serde_qs = "0.12"
simd-json = "0.10.5"
strum = { version = "0.25.0", features = ["derive"] }
strum_macros = "0.25.0"
tokio = { version = "1.31.0", features = ["fs", "io-util"] }
tokio-util = { version = "0.7.8", features = ["io"] }
thiserror = "1.0.44"
tracing = "0.1.37"
typed-builder = "0.15.2"

[dev-dependencies]
tokio = { version = "1.31.0", features = ["macros", "rt"] }
