[package]
name = "kitsune-fe-native"
edition.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = "0.4.0"
dioxus-router = "0.4.0"
sir = { version = "0.4.0", features = [ "dioxus" ] }
